default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: mysql

development:
  <<: *default
  database: planning_poker_development

test:
  <<: *default
  database: planning_poker_test

production:
  <<: *default
  database: planning_poker_production
  username: planning_poker
  password: <%= ENV['PLANNING_POKER_DATABASE_PASSWORD'] %>
